"""empty message

Revision ID: 36a10466e9dd
Revises: b7b58f46308a
Create Date: 2021-03-12 12:37:17.398878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36a10466e9dd'
down_revision = 'b7b58f46308a'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('role')
    # op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # op.drop_constraint('user_role_id_fkey', 'user', type_='foreignkey')
    # op.drop_column('user', 'role_id')
    # # ### end Alembic commands ###


def downgrade():
    pass
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('user', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # op.create_foreign_key('user_role_id_fkey', 'user', 'role', ['role_id'], ['id'])
    # op.drop_column('user', 'is_admin')
    # op.create_table('role',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id', name='role_pkey')
    #)
    # ### end Alembic commands ###
