"""empty message

Revision ID: 593d836a3da5
Revises: 36a10466e9dd
Create Date: 2021-03-12 12:50:40.520911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '593d836a3da5'
down_revision = '36a10466e9dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
